const fs = require('fs');

// ========== DICIONÁRIO OFICIAL D&D 5e PT-BR (GreenRoninBrasil) ==========
// Nomes de magias (inglês -> português oficial)
const SPELL_NAME_MAP = {
  // Cantrips / Truques (Nível 0)
  "Acid Splash": "Esguicho de Ácido",
  "Blade Ward": "Proteção contra Lâminas",
  "Chill Touch": "Toque Gélido",
  "Dancing Lights": "Luzes Dançantes",
  "Druidcraft": "Arte Druídica",
  "Eldritch Blast": "Rajada Mística",
  "Fire Bolt": "Raio de Fogo",
  "Friends": "Amigos",
  "Guidance": "Orientação",
  "Light": "Luz",
  "Mage Hand": "Mão Mágica",
  "Mending": "Remendar",
  "Message": "Mensagem",
  "Minor Illusion": "Ilusão Menor",
  "Poison Spray": "Borrifo de Veneno",
  "Prestidigitation": "Prestidigitação",
  "Produce Flame": "Produzir Chamas",
  "Ray of Frost": "Raio de Gelo",
  "Resistance": "Resistência",
  "Sacred Flame": "Chama Sagrada",
  "Shillelagh": "Shillelagh",
  "Shocking Grasp": "Toque Chocante",
  "Spare the Dying": "Salvar os Moribundos",
  "Thaumaturgy": "Taumaturgia",
  "True Strike": "Golpe Certeiro",
  "Vicious Mockery": "Zombaria Viciosa",
  "Thunderclap": "Trovejada",
  "Control Flames": "Controlar Chamas",
  "Create Bonfire": "Criar Fogueira",
  "Frostbite": "Queimadura de Gelo",
  "Gust": "Rajada",
  "Infestation": "Infestação",
  "Magic Stone": "Pedra Mágica",
  "Mold Earth": "Moldar a Terra",
  "Shape Water": "Modelar Água",
  "Sword Burst": "Explosão de Lâminas",
  "Toll the Dead": "Tocar o Dobre",
  "Word of Radiance": "Palavra de Radiosidade",
  "Green-Flame Blade": "Lâmina de Chama Verde",
  "Booming Blade": "Lâmina Retumbante",

  // Nível 1
  "Alarm": "Alarme",
  "Animal Friendship": "Amizade com Animais",
  "Bane": "Perdição",
  "Burning Hands": "Mãos Ardentes",
  "Charm Person": "Enfeitiçar Pessoa",
  "Color Spray": "Aspersão de Cores",
  "Command": "Comando",
  "Comprehend Languages": "Compreender Idiomas",
  "Create or Destroy Water": "Criar ou Destruir Água",
  "Cure Wounds": "Curar Ferimentos",
  "Detect Evil and Good": "Detectar o Bem e o Mal",
  "Detect Magic": "Detectar Magia",
  "Detect Poison and Disease": "Detectar Veneno e Doenças",
  "Disguise Self": "Disfarçar a Si Mesmo",
  "Dissonant Whispers": "Sussurros Dissonantes",
  "Divine Favor": "Favor Divino",
  "Entangle": "Emaranhar",
  "Expeditious Retreat": "Retirada Apressada",
  "Faerie Fire": "Fogo Feérico",
  "False Life": "Falsa Vida",
  "Feather Fall": "Queda de Pena",
  "Find Familiar": "Encontrar Familiar",
  "Fog Cloud": "Nuvem de Névoa",
  "Goodberry": "Boa Baga",
  "Grease": "Graxa",
  "Guiding Bolt": "Raio Guiado",
  "Healing Word": "Palavra de Cura",
  "Hellish Rebuke": "Represália Infernal",
  "Heroism": "Heroísmo",
  "Hideous Laughter": "Riso Horrível",
  "Hunter's Mark": "Marca do Caçador",
  "Ice Knife": "Faca de Gelo",
  "Identify": "Identificar",
  "Illusory Script": "Escrita Ilusória",
  "Inflict Wounds": "Infligir Ferimentos",
  "Jump": "Saltar",
  "Longstrider": "Passo Longo",
  "Mage Armor": "Armadura de Mago",
  "Magic Missile": "Míssil Mágico",
  "Protection from Evil and Good": "Proteção contra o Bem e o Mal",
  "Purify Food and Drink": "Purificar Comida e Água",
  "Ray of Sickness": "Raio de Doença",
  "Sanctuary": "Santuário",
  "Shield": "Escudo",
  "Shield of Faith": "Escudo da Fé",
  "Silent Image": "Imagem Silenciosa",
  "Sleep": "Sono",
  "Speak with Animals": "Falar com Animais",
  "Tasha's Hideous Laughter": "Gargalhada Horrível de Tasha",
  "Thunderwave": "Onda Trovejante",
  "Unseen Servant": "Servo Invisível",
  "Witch Bolt": "Raio da Bruxa",
  "Bless": "Abençoar",
  "Absorb Elements": "Absorver Elementos",
  "Catapult": "Catapulta",
  "Cause Fear": "Causar Medo",
  "Chaos Bolt": "Raio do Caos",
  "Earth Tremor": "Tremor de Terra",
  "Snare": "Armadilha",
  "Zephyr Strike": "Golpe Zéfiro",

  // Nível 2
  "Aid": "Auxílio",
  "Alter Self": "Alterar a Si Mesmo",
  "Animal Messenger": "Mensageiro Animal",
  "Arcane Lock": "Fechadura Arcana",
  "Augury": "Augúrio",
  "Barkskin": "Pele de Casca",
  "Blindness/Deafness": "Cegueira/Surdez",
  "Blur": "Borrar",
  "Calm Emotions": "Acalmar Emoções",
  "Cloud of Daggers": "Nuvem de Adagas",
  "Continual Flame": "Chama Contínua",
  "Crown of Madness": "Coroa da Loucura",
  "Darkness": "Escuridão",
  "Darkvision": "Visão no Escuro",
  "Detect Thoughts": "Detectar Pensamentos",
  "Dragon's Breath": "Bafo do Dragão",
  "Enhance Ability": "Aprimorar Habilidade",
  "Enlarge/Reduce": "Aumentar/Reduzir",
  "Enthrall": "Fascinar",
  "Find Steed": "Encontrar Corcel",
  "Find Traps": "Encontrar Armadilhas",
  "Flaming Sphere": "Esfera Flamejante",
  "Gentle Repose": "Repouso Gentil",
  "Gust of Wind": "Rajada de Vento",
  "Heat Metal": "Aquecer Metal",
  "Hold Person": "Paralisar Pessoa",
  "Invisibility": "Invisibilidade",
  "Knock": "Destravar",
  "Lesser Restoration": "Restauração Menor",
  "Levitate": "Levitar",
  "Locate Animals or Plants": "Localizar Animais ou Plantas",
  "Locate Object": "Localizar Objeto",
  "Magic Mouth": "Boca Mágica",
  "Magic Weapon": "Arma Mágica",
  "Melf's Acid Arrow": "Flecha de Ácido de Melf",
  "Mirror Image": "Imagem Espelhada",
  "Misty Step": "Passo Nebuloso",
  "Moonbeam": "Raio de Lua",
  "Nystul's Magic Aura": "Aura Mágica de Nystul",
  "Pass without Trace": "Passagem sem Rastros",
  "Prayer of Healing": "Oração de Cura",
  "Protection from Poison": "Proteção contra Veneno",
  "Ray of Enfeeblement": "Raio de Enfraquecer",
  "Rope Trick": "Truque da Corda",
  "See Invisibility": "Ver Invisibilidade",
  "Shatter": "Estilhaçar",
  "Silence": "Silêncio",
  "Spider Climb": "Escalar como Aranha",
  "Spike Growth": "Crescimento de Espinhos",
  "Spiritual Weapon": "Arma Espiritual",
  "Suggestion": "Sugestão",
  "Warding Bond": "Vínculo de Proteção",
  "Web": "Teia",
  "Wristpocket": "Bolso do Pulso",
  "Zone of Truth": "Zona da Verdade",
  "Aganazzar's Scorcher": "Chamuscador de Aganazzar",
  "Dust Devil": "Redemoinho de Poeira",
  "Earthbind": "Prender à Terra",
  "Healing Spirit": "Espírito da Cura",
  "Jim's Glowing Coin": "Moeda Brilhante de Jim",
  "Mental Barrier": "Barreira Mental",
  "Mind Spike": "Pico Mental",
  "Pyrotechnics": "Pirotecnia",
  "Skywrite": "Escrever no Céu",
  "Snilloc's Snowball Swarm": "Tempestade de Bolas de Neve de Snilloc",
  "Vortex Warp": "Dobramento de Vórtice",
  "Warding Wind": "Vento de Proteção",

  // Nível 3
  "Animate Dead": "Animar os Mortos",
  "Aura of Vitality": "Aura de Vitalidade",
  "Beacon of Hope": "Balizador da Esperança",
  "Bestow Curse": "Impor Maldição",
  "Blink": "Piscar",
  "Call Lightning": "Invocar Relâmpago",
  "Clairvoyance": "Clarividência",
  "Conjure Animals": "Convocar Animais",
  "Conjure Barrage": "Convocar Barragem",
  "Counterspell": "Contramagia",
  "Create Food and Water": "Criar Comida e Água",
  "Crusader's Mantle": "Manto do Cruzado",
  "Daylight": "Luz do Dia",
  "Dispel Magic": "Dissipar Magia",
  "Elemental Weapon": "Arma Elemental",
  "Fear": "Medo",
  "Feign Death": "Fingir a Morte",
  "Fireball": "Bola de Fogo",
  "Fly": "Voar",
  "Gaseous Form": "Forma Gasosa",
  "Glyph of Warding": "Glifo de Proteção",
  "Haste": "Aceleração",
  "Hunger of Hadar": "Fome de Hadar",
  "Hypnotic Pattern": "Padrão Hipnótico",
  "Leomund's Tiny Hut": "Cabana Minúscula de Leomund",
  "Life Transference": "Transferência de Vida",
  "Lightning Arrow": "Flecha de Relâmpago",
  "Lightning Bolt": "Raio",
  "Magic Circle": "Círculo Mágico",
  "Major Image": "Imagem Maior",
  "Mass Healing Word": "Palavra de Cura em Massa",
  "Meld into Stone": "Fundir-se com a Pedra",
  "Nondetection": "Indetectável",
  "Plant Growth": "Crescimento Vegetal",
  "Protection from Energy": "Proteção da Energia",
  "Remove Curse": "Remover Maldição",
  "Revivify": "Revivificar",
  "Sending": "Mensagem",
  "Sleet Storm": "Tempestade de Granizo",
  "Slow": "Lentidão",
  "Speak with Dead": "Falar com os Mortos",
  "Speak with Plants": "Falar com Plantas",
  "Spirit Guardians": "Guardiões Espirituais",
  "Stinking Cloud": "Nuvem Fedorenta",
  "Summon Lesser Demons": "Invocar Demônios Menores",
  "Thunder Step": "Passo Trovejante",
  "Tidal Wave": "Onda Tidal",
  "Tiny Servant": "Servo Minúsculo",
  "Tongues": "Línguas",
  "Vampiric Touch": "Toque Vampírico",
  "Wall of Sand": "Muro de Areia",
  "Wall of Water": "Muro de Água",
  "Water Breathing": "Respirar na Água",
  "Water Walk": "Caminhar nas Águas",
  "Wind Wall": "Muro de Vento",
  "Catnap": "Cochilar",
  "Erupting Earth": "Terra em Erupção",
  "Flame Arrows": "Flechas em Chamas",
  "Melf's Minute Meteors": "Meteoros Minúsculos de Melf",
  "Summon Fey": "Invocar o Feérico",
  "Summon Shadowspawn": "Invocar Criatura das Sombras",
  "Summon Undead": "Invocar o Morto-Vivo",

  // Nível 4
  "Arcane Eye": "Olho Arcano",
  "Aura of Life": "Aura de Vida",
  "Aura of Purity": "Aura de Pureza",
  "Banishment": "Banimento",
  "Black Tentacles": "Tentáculos Negros",
  "Blight": "Praga",
  "Compulsion": "Compulsão",
  "Confusion": "Confusão",
  "Conjure Minor Elementals": "Convocar Elementais Menores",
  "Conjure Woodland Beings": "Convocar Seres Florestais",
  "Control Water": "Controlar Água",
  "Death Ward": "Proteção Mortal",
  "Dimension Door": "Porta Dimensional",
  "Divination": "Adivinhação",
  "Dominate Beast": "Dominar Besta",
  "Elemental Bane": "Perdição Elemental",
  "Evard's Black Tentacles": "Tentáculos Negros de Evard",
  "Fabricate": "Fabricar",
  "Fire Shield": "Escudo de Fogo",
  "Freedom of Movement": "Liberdade de Movimentos",
  "Giant Insect": "Inseto Gigante",
  "Grasping Vine": "Videira Apreensora",
  "Greater Invisibility": "Invisibilidade Superior",
  "Guardian of Faith": "Guardião da Fé",
  "Hallucinatory Terrain": "Terreno Alucinatório",
  "Ice Storm": "Tempestade de Gelo",
  "Leomund's Secret Chest": "Baú Secreto de Leomund",
  "Locate Creature": "Localizar Criatura",
  "Mordenkainen's Faithful Hound": "Cão Fiel de Mordenkainen",
  "Mordenkainen's Private Sanctum": "Santuário Privado de Mordenkainen",
  "Otiluke's Resilient Sphere": "Esfera Resiliente de Otiluke",
  "Phantasmal Killer": "Assassino Fantasmal",
  "Polymorph": "Polimorfismo",
  "Raulothim's Psychic Lance": "Lança Psíquica de Raulothim",
  "Sickening Radiance": "Radiância Nauseante",
  "Stone Shape": "Moldar Pedra",
  "Stoneskin": "Pele de Pedra",
  "Storm Sphere": "Esfera da Tempestade",
  "Summon Aberration": "Invocar Aberração",
  "Summon Construct": "Invocar Constructo",
  "Summon Elemental": "Invocar Elemental",
  "Vitriolic Sphere": "Esfera Vitriólica",
  "Wall of Fire": "Muro de Fogo",
  "Watery Sphere": "Esfera de Água",

  // Nível 5
  "Animate Objects": "Animar Objetos",
  "Antilife Shell": "Escudo Anticriaturas Vivas",
  "Arcane Hand": "Mão Arcana",
  "Awaken": "Despertar",
  "Banishing Smite": "Golpe do Banimento",
  "Circle of Power": "Círculo de Poder",
  "Cloudkill": "Matar na Nuvem",
  "Commune": "Comungar",
  "Commune with Nature": "Comungar com a Natureza",
  "Cone of Cold": "Cone de Frio",
  "Conjure Elemental": "Convocar Elemental",
  "Conjure Volley": "Convocar Salva",
  "Contact Other Plane": "Contatar Outro Plano",
  "Contagion": "Contágio",
  "Control Winds": "Controlar Ventos",
  "Creation": "Criação",
  "Dawn": "Alvorecer",
  "Destructive Wave": "Onda Destrutiva",
  "Dispel Evil and Good": "Dissipar o Bem e o Mal",
  "Dominate Person": "Dominar Pessoa",
  "Dream": "Sonho",
  "Enervation": "Enervação",
  "Far Step": "Passo Distante",
  "Flame Strike": "Golpe de Chama",
  "Geas": "Compromisso",
  "Greater Restoration": "Restauração Superior",
  "Hallow": "Consagrar",
  "Hold Monster": "Paralisar Monstro",
  "Holy Weapon": "Arma Sagrada",
  "Immolation": "Imolação",
  "Infernal Calling": "Chamado Infernal",
  "Insect Plague": "Praga de Insetos",
  "Legend Lore": "Conhecimento Lendário",
  "Maelstrom": "Maelstrom",
  "Mass Cure Wounds": "Curar Ferimentos em Massa",
  "Mislead": "Enganar",
  "Modify Memory": "Modificar Memória",
  "Passwall": "Passagem Mural",
  "Planar Binding": "Vínculo Planar",
  "Raise Dead": "Ressuscitar os Mortos",
  "Rary's Telepathic Bond": "Vínculo Telepático de Rary",
  "Reincarnate": "Reencarnar",
  "Scrying": "Escrutinar",
  "Seeming": "Aparência",
  "Steel Wind Strike": "Golpe de Vento de Aço",
  "Swift Quiver": "Aljava Veloz",
  "Synaptic Static": "Estática Sináptica",
  "Telekinesis": "Telecinese",
  "Teleportation Circle": "Círculo de Teletransporte",
  "Transmute Rock": "Transmutar Rocha",
  "Tree Stride": "Passo Arbóreo",
  "Wall of Force": "Muro de Força",
  "Wall of Stone": "Muro de Pedra",
  "Wrath of Nature": "Ira da Natureza",

  // Nível 6
  "Arcane Gate": "Portal Arcano",
  "Blade Barrier": "Barreira de Lâminas",
  "Chain Lightning": "Relâmpago em Cadeia",
  "Circle of Death": "Círculo da Morte",
  "Conjure Fey": "Convocar o Feérico",
  "Contingency": "Contingência",
  "Create Homunculus": "Criar Homúnculo",
  "Create Undead": "Criar Morto-Vivo",
  "Disintegrate": "Desintegrar",
  "Drawmij's Instant Summons": "Convocação Instantânea de Drawmij",
  "Eyebite": "Mordida do Olhar",
  "Find the Path": "Encontrar o Caminho",
  "Flesh to Stone": "Carne em Pedra",
  "Forbiddance": "Proibição",
  "Globe of Invulnerability": "Globo de Invulnerabilidade",
  "Guards and Wards": "Guardas e Vigias",
  "Harm": "Causar Dano",
  "Heal": "Curar",
  "Heroes' Feast": "Banquete dos Heróis",
  "Instant Summons": "Convocação Instantânea",
  "Investiture of Flame": "Investidura de Chamas",
  "Investiture of Ice": "Investidura de Gelo",
  "Investiture of Stone": "Investidura de Pedra",
  "Investiture of Wind": "Investidura de Vento",
  "Irresistible Dance": "Dança Irresistível",
  "Magic Jar": "Jarro Mágico",
  "Mass Suggestion": "Sugestão em Massa",
  "Mental Prison": "Prisão Mental",
  "Move Earth": "Mover a Terra",
  "Otto's Irresistible Dance": "Dança Irresistível de Otto",
  "Primordial Ward": "Proteção Primordial",
  "Programmed Illusion": "Ilusão Programada",
  "Scatter": "Dispersar",
  "Soul Cage": "Gaiola da Alma",
  "Sunbeam": "Raio de Sol",
  "Tasha's Otherworldly Guise": "Aparência Extraplanar de Tasha",
  "Transport via Plants": "Transporte via Plantas",
  "True Seeing": "Visão Verdadeira",
  "Wall of Ice": "Muro de Gelo",
  "Wall of Thorns": "Muro de Espinhos",
  "Wind Walk": "Caminhar no Vento",
  "Word of Recall": "Palavra de Retorno",

  // Nível 7
  "Conjure Celestial": "Convocar Celestial",
  "Crown of Stars": "Coroa de Estrelas",
  "Delayed Blast Fireball": "Bola de Fogo de Explosão Retardada",
  "Divine Word": "Palavra Divina",
  "Etherealness": "Etereidade",
  "Finger of Death": "Dedo da Morte",
  "Fire Storm": "Tempestade de Fogo",
  "Forcecage": "Gaiola de Força",
  "Mirage Arcane": "Miragem Arcana",
  "Mordenkainen's Magnificent Mansion": "Mansão Magnífica de Mordenkainen",
  "Mordenkainen's Sword": "Espada de Mordenkainen",
  "Plane Shift": "Mudança Planar",
  "Power Word Pain": "Palavra de Poder: Dor",
  "Prismatic Spray": "Aspersão Prismática",
  "Project Image": "Projetar Imagem",
  "Regenerate": "Regenerar",
  "Resurrection": "Ressurreição",
  "Reverse Gravity": "Inverter a Gravidade",
  "Sequester": "Sequestrar",
  "Simulacrum": "Simulacro",
  "Symbol": "Símbolo",
  "Teleport": "Teletransporte",
  "Whirlwind": "Redemoinho",

  // Nível 8
  "Abi-Dalzim's Horrid Wilting": "Murcha Horrível de Abi-Dalzim",
  "Animal Shapes": "Formas Animais",
  "Antimagic Field": "Campo Antimágico",
  "Antipathy/Sympathy": "Antipatia/Simpatia",
  "Clone": "Clonar",
  "Control Weather": "Controlar o Clima",
  "Demiplane": "Demiplano",
  "Dominate Monster": "Dominar Monstro",
  "Earthquake": "Terremoto",
  "Feeblemind": "Debilitar Mente",
  "Glibness": "Fluência",
  "Holy Aura": "Aura Sagrada",
  "Illusory Dragon": "Dragão Ilusório",
  "Incendiary Cloud": "Nuvem Incendiária",
  "Maddening Darkness": "Escuridão Enlouquecedora",
  "Maze": "Labirinto",
  "Mind Blank": "Mente em Branco",
  "Power Word Stun": "Palavra de Poder: Atordoar",
  "Sunburst": "Explosão Solar",
  "Telepathy": "Telepatia",
  "Tsunami": "Tsunami",

  // Nível 9
  "Astral Projection": "Projeção Astral",
  "Foresight": "Presciência",
  "Gate": "Portal",
  "Imprisonment": "Aprisionamento",
  "Invulnerability": "Invulnerabilidade",
  "Mass Heal": "Curar em Massa",
  "Mass Polymorph": "Polimorfismo em Massa",
  "Meteor Swarm": "Chuva de Meteoros",
  "Power Word Heal": "Palavra de Poder: Curar",
  "Power Word Kill": "Palavra de Poder: Matar",
  "Prismatic Wall": "Muro Prismático",
  "Psychic Scream": "Grito Psíquico",
  "Shapechange": "Metamorfose",
  "Storm of Vengeance": "Tempestade de Vingança",
  "Time Stop": "Parar o Tempo",
  "True Polymorph": "Polimorfismo Verdadeiro",
  "True Resurrection": "Ressurreição Verdadeira",
  "Weird": "Pesadelo",
  "Wish": "Desejo",
};

// Dicionário de termos técnicos para usar nas descrições
const TERM_MAP = {
  // Saves
  "Dexterity saving throw": "teste de resistência de Destreza",
  "Strength saving throw": "teste de resistência de Força",
  "Constitution saving throw": "teste de resistência de Constituição",
  "Intelligence saving throw": "teste de resistência de Inteligência",
  "Wisdom saving throw": "teste de resistência de Sabedoria",
  "Charisma saving throw": "teste de resistência de Carisma",
  "saving throw": "teste de resistência",
  "saving throws": "testes de resistência",
  // Conditions
  "charmed": "enfeitiçado",
  "frightened": "amedrontado",
  "paralyzed": "paralisado",
  "poisoned": "envenenado",
  "restrained": "imobilizado",
  "stunned": "atordoado",
  "unconscious": "inconsciente",
  "blinded": "cego",
  "deafened": "ensurdecido",
  "incapacitated": "incapacitado",
  "prone": "caído",
  "grappled": "agarrado",
  "exhaustion": "exaustão",
  "petrified": "petrificado",
  "invisible": "invisível",
  // Damage types
  "acid damage": "dano de ácido",
  "cold damage": "dano de frio",
  "fire damage": "dano de fogo",
  "force damage": "dano de força",
  "lightning damage": "dano de raio",
  "necrotic damage": "dano necrótico",
  "piercing damage": "dano perfurante",
  "poison damage": "dano de veneno",
  "psychic damage": "dano psíquico",
  "radiant damage": "dano radiante",
  "slashing damage": "dano cortante",
  "thunder damage": "dano sônico",
  "bludgeoning damage": "dano de concussão",
  // Common terms
  "concentration": "concentração",
  "bonus action": "ação bônus",
  "reaction": "reação",
  "opportunity attack": "ataque de oportunidade",
  "hit points": "pontos de vida",
  "hit point": "ponto de vida",
  "spell attack": "ataque de magia",
  "attack roll": "jogada de ataque",
  "ability check": "teste de habilidade",
  "spell slot": "espaço de magia",
  "spell slots": "espaços de magia",
  "spellcasting ability": "atributo de conjuração",
  "spell save DC": "CD de resistência de magia",
  "within range": "dentro do alcance",
  "long rest": "descanso longo",
  "short rest": "descanso curto",
  "creature": "criatura",
  "creatures": "criaturas",
  "willing creature": "criatura voluntária",
  "willing creatures": "criaturas voluntárias",
  "target": "alvo",
  "targets": "alvos",
  "round": "rodada",
  "rounds": "rodadas",
  "minute": "minuto",
  "minutes": "minutos",
  "hour": "hora",
  "hours": "horas",
  "action": "ação",
  "actions": "ações",
  "movement": "movimento",
  "speed": "velocidade",
  "proficiency bonus": "bônus de proficiência",
  "higher level": "nível superior",
  "spell level": "nível de magia",
  "until the spell ends": "até a magia terminar",
  "while the spell is active": "enquanto a magia estiver ativa",
  "you can see": "que você possa ver",
  "within 60 feet": "a até 18 metros",
  "within 30 feet": "a até 9 metros",
  "within 10 feet": "a até 3 metros",
  "within 5 feet": "a até 1,5 metro",
  "60 feet": "18 metros",
  "30 feet": "9 metros",
  "15 feet": "4,5 metros",
  "10 feet": "3 metros",
  "5 feet": "1,5 metro",
  "1 mile": "1,5 quilômetro",
  "120 feet": "36 metros",
  "90 feet": "27 metros",
  "60-foot": "18 metros",
  "30-foot": "9 metros",
  "15-foot": "4,5 metros",
  "10-foot": "3 metros",
  "5-foot": "1,5 metro",
  "20-foot cube": "cubo de 6 metros",
  "10-foot cube": "cubo de 3 metros",
  "20-foot radius": "raio de 6 metros",
  "10-foot radius": "raio de 3 metros",
  "disadvantage": "desvantagem",
  "advantage": "vantagem",
  "melee weapon attack": "ataque corpo a corpo com arma",
  "ranged weapon attack": "ataque à distância com arma",
  "melee spell attack": "ataque de magia corpo a corpo",
  "ranged spell attack": "ataque de magia à distância",
  "hit": "sucesso",
  "miss": "falha",
  "On a hit": "No sucesso",
  "on a failed save": "em um teste de resistência falho",
  "on a successful save": "em um teste de resistência bem-sucedido",
  "half as much damage": "metade do dano",
  "twice as much damage": "o dobro do dano",
  "1 minute": "1 minuto",
  "10 minutes": "10 minutos",
  "8 hours": "8 horas",
  "24 hours": "24 horas",
  "7 days": "7 dias",
  "Instantaneous": "Instantâneo",
  "Until dispelled": "Até ser dissipada",
  "up to 1 minute": "até 1 minuto",
  "up to 10 minutes": "até 10 minutos",
  "up to 1 hour": "até 1 hora",
  "up to 8 hours": "até 8 horas",
  "up to 24 hours": "até 24 horas",
  "Concentration, up to 1 minute": "Concentração, até 1 minuto",
  "Concentration, up to 10 minutes": "Concentração, até 10 minutos",
  "Concentration, up to 1 hour": "Concentração, até 1 hora",
  "Concentration, up to 8 hours": "Concentração, até 8 horas",
  "Concentration, up to 24 hours": "Concentração, até 24 horas",
  "beast": "besta",
  "beasts": "bestas",
  "undead": "mortos-vivos",
  "fiend": "inimigo",
  "fiends": "inimigos",
  "celestial": "celestial",
  "celestials": "celestiais",
  "construct": "constructo",
  "constructs": "constructos",
  "elemental": "elemental",
  "elementals": "elementais",
  "fey": "feérico",
  "humanoid": "humanoide",
  "humanoids": "humanoides",
  "plant": "planta",
  "plants": "plantas",
  "monstrosity": "monstruosidade",
  "dragon": "dragão",
  "dragons": "dragões",
  "giant": "gigante",
  "giants": "gigantes",
  "ooze": "gosma",
  "At Higher Levels": "Em Níveis Superiores",
  "When you cast this spell using a spell slot of": "Quando você conjura essa magia usando um espaço de magia de",
  "When you cast this spell": "Quando você conjura essa magia",
  "you cast the spell": "você conjura a magia",
  "spell ends": "magia termina",
  "You summon": "Você convoca",
  "You create": "Você cria",
  "You conjure": "Você conjura",
  "You cause": "Você causa",
  "choose one": "escolha uma",
  "choose two": "escolha duas",
  "choose up to": "escolha até",
  "or higher": "ou superior",
  "for each slot level above": "para cada nível de espaço acima",
  "Constitution modifier": "modificador de Constituição",
  "Wisdom modifier": "modificador de Sabedoria",
  "Intelligence modifier": "modificador de Inteligência",
  "Strength modifier": "modificador de Força",
  "Dexterity modifier": "modificador de Destreza",
  "Charisma modifier": "modificador de Carisma",
};

// Traduções de duração
const DURATION_MAP = {
  "Instantaneous": "Instantâneo",
  "1 round": "1 rodada",
  "Up to 1 minute": "Até 1 minuto",
  "1 minute": "1 minuto",
  "Up to 10 minutes": "Até 10 minutos",
  "10 minutes": "10 minutos",
  "Up to 1 hour": "Até 1 hora",
  "1 hour": "1 hora",
  "Up to 8 hours": "Até 8 horas",
  "8 hours": "8 horas",
  "Up to 24 hours": "Até 24 horas",
  "24 hours": "24 horas",
  "Until dispelled": "Até ser dissipada",
  "Until dispelled or triggered": "Até ser dissipada ou acionada",
  "7 days": "7 dias",
  "10 days": "10 dias",
  "30 days": "30 dias",
  "Concentration, up to 1 minute": "Concentração, até 1 minuto",
  "Concentration, up to 10 minutes": "Concentração, até 10 minutos",
  "Concentration, up to 1 hour": "Concentração, até 1 hora",
  "Concentration, up to 8 hours": "Concentração, até 8 horas",
  "Concentration, up to 24 hours": "Concentração, até 24 horas",
  "Special": "Especial",
};

// Traduções de school
const SCHOOL_MAP = {
  "Abjuration": "Abjuração",
  "Conjuration": "Conjuração",
  "Divination": "Adivinhação",
  "Enchantment": "Encantamento",
  "Evocation": "Evocação",
  "Illusion": "Ilusão",
  "Necromancy": "Necromancia",
  "Transmutation": "Transmutação",
};

function applyTermMap(text, termMap) {
  let result = text;
  // Apply longer phrases first to avoid partial replacements
  const sortedKeys = Object.keys(termMap).sort((a, b) => b.length - a.length);
  for (const key of sortedKeys) {
    // Case-insensitive replacement, preserve original casing of replacement
    const regex = new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');
    result = result.replace(regex, (match) => {
      // If original starts with uppercase, capitalize replacement
      if (match[0] === match[0].toUpperCase() && match[0] !== match[0].toLowerCase()) {
        const repl = termMap[key];
        return repl.charAt(0).toUpperCase() + repl.slice(1);
      }
      return termMap[key];
    });
  }
  return result;
}

// Read the file
let content = fs.readFileSync('src/utils/dndSpells.ts', 'utf8');

// Parse as JS object (it's a TS file with export, so we do a text replacement approach)
// We'll use regex to find and replace each spell

let translated = 0;
let nameTranslated = 0;

// Step 1: Translate spell names
for (const [en, pt] of Object.entries(SPELL_NAME_MAP)) {
  const escapedEn = en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`"name": "${escapedEn}"`, 'g');
  const before = content;
  content = content.replace(regex, `"name": "${pt}"`);
  if (content !== before) nameTranslated++;
}

console.log(`Names translated: ${nameTranslated}/${Object.keys(SPELL_NAME_MAP).length}`);

// Step 2: Translate school
for (const [en, pt] of Object.entries(SCHOOL_MAP)) {
  const escapedEn = en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`"school": "${escapedEn}"`, 'g');
  content = content.replace(regex, `"school": "${pt}"`);
}

// Step 3: Translate durations
for (const [en, pt] of Object.entries(DURATION_MAP)) {
  const escapedEn = en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`"duration": "${escapedEn}"`, 'gi');
  content = content.replace(regex, `"duration": "${pt}"`);
}

// Step 4: Apply term translations to descriptions
// Find all description values and translate them
content = content.replace(/"description": "((?:[^"\\]|\\.)*)"/g, (match, desc) => {
  // Unescape
  let text = desc.replace(/\\n/g, '\n').replace(/\\"/g, '"').replace(/\\\\/g, '\\');
  // Apply term map
  text = applyTermMap(text, TERM_MAP);
  // Re-escape
  text = text.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
  translated++;
  return `"description": "${text}"`;
});

console.log(`Descriptions processed: ${translated}`);

// Write back
fs.writeFileSync('src/utils/dndSpells.ts', content, 'utf8');
console.log('Done! Spells translated to Portuguese.');
