export interface Spell {
  name: string;
  level: number; // 0 for Cantrip, 1, 2, 3
  classes: string[]; // ['Mago', 'Clérigo', 'Paladino', 'Bardo', 'Druida', 'Bruxo', 'Feiticeiro', 'Patrulheiro']
  school: string;
  castingTime: string;
  range: string;
  duration: string;
  description: string;
}

export const SPELLS_DATABASE: Spell[] = [
  // --- CANTRIPS (TRUQUES) ---
  {
    name: 'Rajada Mística (Eldritch Blast)',
    level: 0,
    classes: ['Bruxo'],
    school: 'Evocação',
    castingTime: '1 ação',
    range: '36 metros',
    duration: 'Instantâneo',
    description: 'Dispara um feixe de energia mágica. Ataque mágico à distância causa 1d10 de dano de força.',
  },
  {
    name: 'Prestidigitação (Prestidigitation)',
    level: 0,
    classes: ['Mago', 'Bardo', 'Bruxo', 'Feiticeiro'],
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '3 metros',
    duration: 'Até 1 hora',
    description: 'Realiza pequenos truques mágicos sensoriais, acende/apaga velas, limpa/suja pequenos objetos ou esquenta/esfria comida.',
  },
  {
    name: 'Mãos de Mago (Mage Hand)',
    level: 0,
    classes: ['Mago', 'Bardo', 'Bruxo', 'Feiticeiro'],
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '9 metros',
    duration: '1 minuto',
    description: 'Cria uma mão espectral flutuante que pode manipular objetos, abrir portas destrancadas ou carregar itens de até 5 kg.',
  },
  {
    name: 'Rajada de Fogo (Fire Bolt)',
    level: 0,
    classes: ['Mago', 'Feiticeiro'],
    school: 'Evocação',
    castingTime: '1 ação',
    range: '36 metros',
    duration: 'Instantâneo',
    description: 'Arremessa uma fagulha de fogo contra uma criatura ou objeto. Causa 1d10 de dano de fogo.',
  },
  {
    name: 'Raio de Gelo (Ray of Frost)',
    level: 0,
    classes: ['Mago', 'Feiticeiro'],
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros',
    duration: 'Instantâneo',
    description: 'Um raio azul-gelo dispara. Causa 1d8 de dano de frio e reduz o deslocamento do alvo em 3 metros por 1 rodada.',
  },
  {
    name: 'Orientação (Guidance)',
    level: 0,
    classes: ['Clérigo', 'Druida'],
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Concentração, até 1 minuto',
    description: 'Concede +1d4 em um teste de habilidade à escolha do alvo tocado.',
  },
  {
    name: 'Chama Sagrada (Sacred Flame)',
    level: 0,
    classes: ['Clérigo'],
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros',
    duration: 'Instantâneo',
    description: 'O alvo deve passar num teste de Destreza ou sofrer 1d8 de dano radiante (ignora cobertura).',
  },
  {
    name: 'Taumaturgia (Thaumaturgy)',
    level: 0,
    classes: ['Clérigo'],
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '9 metros',
    duration: 'Até 1 minuto',
    description: 'Cria pequenas manifestações de poder divino: voz amplificada, chamas tremeluzentes ou portas abrindo.',
  },
  {
    name: 'Luz (Light)',
    level: 0,
    classes: ['Mago', 'Clérigo', 'Bardo', 'Feiticeiro'],
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '1 hora',
    description: 'Faz um objeto tocado brilhar com luz brilhante em um raio de 6 metros.',
  },

  // --- LEVEL 1 SPELLS ---
  {
    name: 'Marca do Caçador (Hunter\'s Mark)',
    level: 1,
    classes: ['Patrulheiro'],
    school: 'Adivinhação',
    castingTime: '1 ação bônus',
    range: '27 metros',
    duration: 'Concentração, até 1 hora',
    description: 'Você marca um inimigo. Seus ataques com arma contra ele causam +1d6 de dano físico extra.',
  },
  {
    name: 'Bruxaria (Hex)',
    level: 1,
    classes: ['Bruxo'],
    school: 'Encantamento',
    castingTime: '1 ação bônus',
    range: '27 metros',
    duration: 'Concentração, até 1 hora',
    description: 'Você amaldiçoa uma criatura. Seus ataques contra ela causam +1d6 de dano necrótico extra e dão desvantagem num teste de atributo.',
  },
  {
    name: 'Fogo Fátuo (Faerie Fire)',
    level: 1,
    classes: ['Bardo', 'Druida'],
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros',
    duration: 'Concentração, até 1 minuto',
    description: 'Criaturas em uma área de cubo de 6m falham em Destreza ou brilham, dando Vantagem em jogadas de ataque contra elas.',
  },
  {
    name: 'Mísseis Mágicos (Magic Missile)',
    level: 1,
    classes: ['Mago', 'Feiticeiro'],
    school: 'Evocação',
    castingTime: '1 ação',
    range: '36 metros',
    duration: 'Instantâneo',
    description: 'Cria três dardos de força infalíveis. Cada dardo causa 1d4 + 1 de dano de força.',
  },
  {
    name: 'Escudo Arcano (Shield)',
    level: 1,
    classes: ['Mago', 'Feiticeiro'],
    school: 'Abjuração',
    castingTime: '1 reação',
    range: 'Pessoal',
    duration: '1 rodada',
    description: 'Concede +5 na AC, incluindo contra o ataque gatilho, e imunidade a Mísseis Mágicos.',
  },
  {
    name: 'Onda de Choque (Thunderwave)',
    level: 1,
    classes: ['Mago', 'Bardo', 'Druida', 'Feiticeiro'],
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Pessoal (cubo de 4,5m)',
    duration: 'Instantâneo',
    description: 'Criaturas na área rolam Constituição ou sofrem 2d8 de dano trovejante e são empurradas 3 metros.',
  },
  {
    name: 'Armadura Arcana (Mage Armor)',
    level: 1,
    classes: ['Mago', 'Feiticeiro'],
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '8 horas',
    description: 'Concede AC base = 13 + Modificador de Destreza a um alvo sem armadura.',
  },
  {
    name: 'Curar Ferimentos (Cure Wounds)',
    level: 1,
    classes: ['Clérigo', 'Paladino', 'Bardo', 'Druida', 'Patrulheiro'],
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Instantâneo',
    description: 'Cura uma criatura tocada em 1d8 + modificador de habilidade de conjuração.',
  },
  {
    name: 'Palavra de Cura (Healing Word)',
    level: 1,
    classes: ['Clérigo', 'Bardo', 'Druida'],
    school: 'Evocação',
    castingTime: '1 ação bônus',
    range: '18 metros',
    duration: 'Instantâneo',
    description: 'Cura uma criatura visível em 1d4 + modificador de habilidade de conjuração.',
  },
  {
    name: 'Bênção (Bless)',
    level: 1,
    classes: ['Clérigo', 'Paladino'],
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '9 metros',
    duration: 'Concentração, até 1 minuto',
    description: 'Até três aliados ganham +1d4 nas jogadas de ataque e testes de resistência.',
  },
  {
    name: 'Escudo da Fé (Shield of Faith)',
    level: 1,
    classes: ['Clérigo', 'Paladino'],
    school: 'Abjuração',
    castingTime: '1 ação bônus',
    range: '18 metros',
    duration: 'Concentração, até 10 minutos',
    description: 'Concede +2 de bônus na AC de uma criatura visível.',
  },
  {
    name: 'Destruição Trovejante (Thunderous Smite)',
    level: 1,
    classes: ['Paladino'],
    school: 'Evocação',
    castingTime: '1 ação bônus',
    range: 'Pessoal',
    duration: 'Concentração, até 1 minuto',
    description: 'Seu próximo ataque causa +2d6 de dano trovejante e pode derrubar o alvo no chão.',
  },
  {
    name: 'Destruição Colérica (Wrathful Smite)',
    level: 1,
    classes: ['Paladino'],
    school: 'Evocação',
    castingTime: '1 ação bônus',
    range: 'Pessoal',
    duration: 'Concentração, até 1 minuto',
    description: 'Seu próximo ataque causa +1d6 de dano psíquico e pode amedrontar o alvo.',
  },
  {
    name: 'Divine Smite (Destruição Divina)',
    level: 1,
    classes: ['Paladino'],
    school: 'Evocação',
    castingTime: 'Especial (ao acertar um ataque)',
    range: 'Pessoal',
    duration: 'Instantâneo',
    description: 'Consome um espaço de magia para causar +2d8 de dano radiante no 1º nível, mais +1d8 por nível de espaço acima do 1º (máx. 5d8), e +1d8 contra mortos-vivos ou corruptores.',
  },


  // --- LEVEL 2 SPELLS ---
  {
    name: 'Crescer Espinhos (Spike Growth)',
    level: 2,
    classes: ['Druida', 'Patrulheiro'],
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '45 metros',
    duration: 'Concentração, até 10 minutos',
    description: 'O solo se cobre de espinhos. A área vira terreno difícil e criaturas sofrem 2d4 de dano de perfuração para cada 1,5m que andarem.',
  },
  {
    name: 'Invisibilidade (Invisibility)',
    level: 2,
    classes: ['Mago', 'Bardo', 'Bruxo', 'Feiticeiro'],
    school: 'Ilusão',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Concentração, até 1 hora',
    description: 'Torna um alvo invisível. A magia acaba se ele atacar ou conjurar uma magia.',
  },
  {
    name: 'Passo Nebuloso (Misty Step)',
    level: 2,
    classes: ['Mago', 'Bruxo', 'Feiticeiro'],
    school: 'Conjuração',
    castingTime: '1 ação bônus',
    range: 'Pessoal',
    duration: 'Instantâneo',
    description: 'Teleporta-se instantaneamente para um local visível dentro de 9 metros.',
  },
  {
    name: 'Despedaçar (Shatter)',
    level: 2,
    classes: ['Mago', 'Bardo', 'Bruxo', 'Feiticeiro'],
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros',
    duration: 'Instantâneo',
    description: 'Causa 3d8 de dano trovejante em uma esfera de 3 metros de raio.',
  },
  {
    name: 'Teia (Web)',
    level: 2,
    classes: ['Mago', 'Feiticeiro'],
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '18 metros',
    duration: 'Concentração, até 1 hora',
    description: 'Cria teias pegajosas que impedem o movimento de criaturas na área.',
  },
  {
    name: 'Arma Espiritual (Spiritual Weapon)',
    level: 2,
    classes: ['Clérigo'],
    school: 'Evocação',
    castingTime: '1 ação bônus',
    range: '18 metros',
    duration: '1 minuto',
    description: 'Cria uma arma flutuante que causa 1d8 + modificador de Sabedoria como dano com ações bônus.',
  },
  {
    name: 'Restauração Menor (Lesser Restoration)',
    level: 2,
    classes: ['Clérigo', 'Paladino', 'Bardo', 'Druida', 'Patrulheiro'],
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Instantâneo',
    description: 'Cura cegueira, surdez, paralisia ou envenenamento em um alvo.',
  },
  {
    name: 'Oração de Cura (Prayer of Healing)',
    level: 2,
    classes: ['Clérigo'],
    school: 'Evocação',
    castingTime: '10 minutos',
    range: '9 metros',
    duration: 'Instantâneo',
    description: 'Cura até seis aliados em 2d8 + modificador de Sabedoria.',
  },
  {
    name: 'Ajuda (Aid)',
    level: 2,
    classes: ['Clérigo', 'Paladino'],
    school: 'Abjuração',
    castingTime: '1 ação',
    range: '9 metros',
    duration: '8 horas',
    description: 'Aumenta em 5 o HP máximo e atual de até três aliados.',
  },

  // --- LEVEL 3 SPELLS ---
  {
    name: 'Chamar Relâmpagos (Call Lightning)',
    level: 3,
    classes: ['Druida'],
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '36 metros',
    duration: 'Concentração, até 10 minutos',
    description: 'Invoca uma nuvem de tempestade. Com sua ação, você pode fazer um relâmpago cair causando 3d10 de dano elétrico.',
  },
  {
    name: 'Bola de Fogo (Fireball)',
    level: 3,
    classes: ['Mago', 'Feiticeiro'],
    school: 'Evocação',
    castingTime: '1 ação',
    range: '45 metros',
    duration: 'Instantâneo',
    description: 'Explosão que causa 8d6 de dano de fogo em uma esfera de 6 metros de raio.',
  },
  {
    name: 'Velocidade (Haste)',
    level: 3,
    classes: ['Mago', 'Feiticeiro'],
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '9 metros',
    duration: 'Concentração, até 1 minuto',
    description: 'Dobra a velocidade, concede +2 na AC e uma ação adicional por turno a um alvo.',
  },
  {
    name: 'Voo (Fly)',
    level: 3,
    classes: ['Mago', 'Feiticeiro'],
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Concentração, até 10 minutos',
    description: 'Concede deslocamento de voo de 18 metros a uma criatura tocada.',
  },
  {
    name: 'Contramagia (Counterspell)',
    level: 3,
    classes: ['Mago', 'Bruxo', 'Feiticeiro'],
    school: 'Abjuração',
    castingTime: '1 reação',
    range: '18 metros',
    duration: 'Instantâneo',
    description: 'Interrompe o processo de conjuração de outra criatura.',
  },
  {
    name: 'Espíritos Guardiões (Spirit Guardians)',
    level: 3,
    classes: ['Clérigo'],
    school: 'Conjuração',
    castingTime: '1 ação',
    range: 'Pessoal (4,5m de raio)',
    duration: 'Concentração, até 10 minutos',
    description: 'Espíritos divinos cercam você. Alvos na área sofrem 3d8 de dano radiante ou necrótico.',
  },
  {
    name: 'Revivificar (Revivify)',
    level: 3,
    classes: ['Clérigo', 'Paladino'],
    school: 'Necromancia',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Instantâneo',
    description: 'Retorna à vida com 1 HP uma criatura que morreu no último minuto.',
  },
];
